services:
  - type: web
    name: emomirror
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: MODEL_NAME_OR_PATH
        value: /app/Wav2vec-2.0
      - key: LLM_API_HOST
        value: api.chatanywhere.tech
      - key: LLM_MODEL
        value: gpt-4o
      - key: LLM_API_KEY
        sync: false
